apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clamav_mirror.fullname" . }}
  labels:
    {{- include "clamav_mirror.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clamav_mirror.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clamav_mirror.selectorLabels" . | nindent 8 }}
    spec:
      {{- if or .Values.deployment.volumes.mountCustomPvc }}
      volumes:
      {{- end }}
        {{- if or .Values.deployment.volumes.mountCustomPvc }}
        - name: {{ .Values.deployment.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.deployment.volumes.persistentVolumeClaim }}
        {{- end }}
    
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clamav_mirror.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name | quote }}
          ports:
            - containerPort: {{ .Values.service.api.port }}
              name: clamav-mirror-api
              protocol: TCP
          {{- if .Values.deployment.volumes.mountCustomPvc }}
          volumeMounts:
          {{- end }}
            {{- if or .Values.deployment.volumes.mountCustomPvc }}
            - mountPath: {{ .Values.deployment.volumes.mountPath | quote }}
              name: {{ .Values.deployment.volumes.name }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
