# Default values for clamav-mirror.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# nameOverride -- override the name of the clamav chart
nameOverride: ""

# fullnameOverride -- override the full name of the clamav chart
fullnameOverride: ""

service:
  # service.port -- The port to be used by the clamav service
  port: 443

clamavMirror:
  replicaCount: 1
  # clamavMirror.image -- The clamav-mirror docker image
  image: 151732681343.dkr.ecr.us-west-2.amazonaws.com/clamav-mirror
  #  clamavMirror.version -- The clamav-mirror docker image version - defaults to .Chart.appVersion
  version: "b232b5cd206fe294c37267471e7142c2096147df"
  serviceAccountName: "service-account-name"
  # clamavMirror.resources -- The resource requests and limits for the clamav-mirror service
  resources:
    requests:
      cpu: 400m
      memory: 1000M
    limits:
      cpu: 800m
      memory: 2000M
  cvdUpdate:
    # clamavmirror.cvdUpdate.cvdCron -- DNS based check to update the local database, only new files are downloaded
    cvdCron: "*/10 * * * *"
    # clamavmirror.cvdUpdate.MirrorCron -- Frequency to rsync changes to mirror - defaults to every hour
    mirrorCron: "0 * * * *"
  metricsPort: 9090
  volume:
    name: persistent-volume-name
    pvcName: persistent-volume-claim-name
    mountPath: "/home/clam"
  origin:
    hostname: "127.0.0.1"
    port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  pathType: Prefix
