apiVersion: v2
name: clamav
description: An Open-Source antivirus engine for detecting trojans, viruses, malware & other malicious threats. Using Mailu docker image.
type: application
version: 3.0.10
appVersion: "1.3.0"
