{{ if and .Values.kellnr.postgres.enabled (not (empty .Values.kellnr.postgres.pwd)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kellnr.postgres.pwdSecretRef.name }}
stringData:
  {{ .Values.kellnr.postgres.pwdSecretRef.key }}: "{{ .Values.kellnr.postgres.pwd }}"
{{- end }}
